platform: linux

image_resource:
  type: docker-image
  source:
    repository: viniciusccarvalho/docker-jdk
    tag: "latest"

inputs:
  - name: spring-music

run:
  path: "spring-music/gradlew"
  args: ["-b","spring-music/build.gradle","build"]
