resources:
  - name: spring-music
    type: git
    source:
      branch: master
      uri: https://github.com/scottfrederick/spring-music.git
  - name: pipelines
    type: git
    source:
      branch: master
      uri: https://github.com/viniciusccarvalho/concourse-demos
  - name: pcf
    type: cf
    source:
      api: {{pcf-api}}
      organization: {{pcf-organization}}
      username: {{deploy-username}}
      password: {{deploy-password}}
      skip_cert_check: true
      space: {{pcf-space}}

jobs:
  - name: build-app
    plan:
      - aggregate:
        - get: spring-music
          trigger: true
        - get: pipelines
          trigger: true
      - task: package
        file: pipelines/spring-music/ci/package.yml
