resources:
  - name: spring-music
    type: git
    source:
      branch: master
      uri: https://github.com/scottfrederick/spring-music.git
  - name: pcf
    type: cf
    source:
      api: {{pcf-api}}
      organization: {{pcf-organization}}
      username: {{deploy-username}}
      password: {{deploy-password}}
      skip_cert_check: true
      space: {{pcf-space}}
